### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by iAmRenzo** [louisdh/textor#14]
I have dark mode and there are two things I noticed:
- the loading screen is bright white. Can't this be changed to darkness if the user selected 'dark'.
- dark mode is grayish. Can there be (a little) more black? For the iPhone X oled screens.

**Comment by louisdh** [comment]
• Unfortunately the loading screen can't be changed based on the theme, that's a restriction from Apple.
• We could add a 3rd theme ("pure black"), but the document browser from Apple only has a "gray" dark theme. So we couldn't make the whole app black.

**Comment by iAmRenzo** [comment]
Too bad! Apple should make work of the official dark mode on iOS. With and OLED screen they should have introduced it with the release of the iPhone X.
Thanks for the update.
