### ISSUE TITLE
Setting to toggle line wrap

### ISSUE THREAD

**Issue by metbril** [louisdh/textor#18]
Currently the editor automatically wraps long lines.
I sometimes use it as a code editor. In those cases I would like to toggle wrap off.
Could you add this as an extra setting? Nothing fancy, just on/off.

**Comment by aamct2** [comment]
I suspect this is actually going to be a bigger change than one might anticipate. `UITextView`, which is what is being used, doesn't have a way to turn off word wrapping built-in. You'd likely have to drop down into the Core Text functionality that underlies it and need to manually manage the layout. Or we'd have to find a dependency that offers us this functionality.

**Comment by metbril** [comment]
Too bad, but I understand your reasoning.
