### ISSUE TITLE
Scrolling is broken in 1.1

### ISSUE THREAD

**Issue by LeoNatan** [louisdh/textor#9]
Hey!

Very cool app!

Scrolling seems to be broken with 1.1. On a new document or a short one, it’s not possible to scroll at all, and thus not possible to dismiss the keyboard.

**Comment by louisdh** [comment]
If I understand you correctly, you're saying that scrolling works fine when there's text that doesn't fit the screen. But scrolling to dismiss the keyboard doesn't work when there's no text offscreen (and thus no scroll bar)?

**Comment by LeoNatan** [comment]
Yes, exactly. It's one of the properties on `UIScrollView` that controls this. I think it's `alwaysBounces`.

**Comment by LeoNatan** [comment]
It is exactly that:

>If this property is set to YES and bounces is YES, vertical dragging is allowed even if the content is smaller than the bounds of the scroll view. The default value is NO.

**Comment by louisdh** [comment]
Fixed e866a6938bec5592b3d0584eabe4939a665f9d2f

**Comment by LeoNatan** [comment]
Thanks
